@startuml
start
if ((1..2).random() == 1?) then (yes)
    :ActivityStart();
else (no)
    :ActivityAlternativeStart();
endif
switch ((1..3).random())
case ("1")
    :ActivityPath1A();
    :ActivityPath1B();
case ("2")
    :ActivityPath2();
case ("else")
    :ActivityPath3();
endswitch
repeat :for i in (1..3);
    :ActivityLoop(i);
repeat while (next i in (1..3)) is (true)
:ActivityEnd();
stop
@enduml