@startuml
start
repeat :for i in (1..3);
    :ActivityLoop(i);
repeat while (next i in (1..3)) is (true)
while (counter < 2) is (true)
    :ActivityWhileLoop(counter);
endwhile
:ActivityEnd();
stop
@enduml
