@startuml
start
:ActivityStart();
if ((1..10).random() > 5?) then (yes)
    :ActivityA();
    switch ((1..3).random())
    case ("1")
        :ActivityX();
    case ("2")
        :ActivityY();
    case ("else")
        :ActivityZ();
    endswitch
else (no)
    :ActivityB();
    repeat :for i in (1..2);
        :ActivityLoop(i);
    repeat while (next i in (1..2)) is (true)
endif
:ActivityEnd();
stop
@enduml