@startuml
start
:ActivityStart();
if ((1..10).random() > 5?) then (yes)
    :ActivityA();
    switch ((1..3).random())
    case ("1")
        :ActivityX();
    case ("2")
        :ActivityY();
    case ("")
        :ActivityZ();
    endswitch
else (no)
    :ActivityB();
    repeat (1..2 as i)
        :ActivityLoop(i);
    endrepeat
endif
:ActivityEnd();
stop
@enduml
