@startuml
start
switch (listOf("NEW", "PROCESSING", "COMPLETED").random())
case (""NEW"")
    :ActivityNew();
    :ActivityInit();
case (""PROCESSING"")
    :ActivityProcessing();
case (""COMPLETED"")
    :ActivityCompleted();
case ("else")
    :ActivityUnknown();
endswitch
stop
@enduml
