@startuml
start
switch ((1..4).random())
case ("1, 2")
    :ActivityCondition12();
case ("3")
    :ActivityCondition3();
case ("else")
    :ActivityConditionElse();
endswitch
switch ((1..2).random())
case ("1")
    :ActivitySecondWhen1();
case ("else")
    :ActivitySecondWhen2();
endswitch
stop
@enduml
